### PR TITLE
Fix clippy warnings

### PR DESCRIPTION
**Pull request by peterstuart**
This fixes all the warnings that the latest version of clippy shows for this repo.

### CODE REVIEW

**Comment by jamwaffles** [comment]
Thanks for the cleanup! Similarly to https://github.com/embedded-graphics/bdf/pull/27#issuecomment-999510509, we just need to wait for #28 to fix the CI.

**Comment by jamwaffles** [comment]
#28 just went in, so please rebase your two PRs and we can get those rolling too.

**Comment by peterstuart** [comment]
@jamwaffles Done. #27 may fail because of the clippy warnings fixed by this PR so I might need to rebase again once this one is merged.

**Comment by jamwaffles** [comment]
Looks like it passed just fine. Thanks again!

**Pull request merged**
